[project]
authors = [
  {name = "Ismael Mendoza", email = "imendoza@umich.edu"},
  {name = "Michael Schneider"},
  {name = "Bob Armstrong"},
  {name = "Biswajit Biswas"},
]
classifiers = [
  "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "description"]
name = "bayes_pipelines_pixels"
readme = "README.md"
requires-python = ">=3.7"

[tool.flit.sdist]
include = ["bpp/"]

[project.urls]
Home = "https://github.com/LSSTDESC/bayesian-pipelines-pixels"

[dependencies]
galsim = "^2.3.4"
numpy = "^1.22.3"

[dev-dependencies]
pytest = "^7.1.2"

[tool.flit.module]
name = "bpp"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.pytest.ini_options]
addopts = "-ra"
minversion = "6.0"
testpaths = [
  "tests",
]
