[tool.pytest.ini_options]
addopts = "-ra"
minversion = "7.0.0"
testpaths = [
  "tests",
]

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88 # black default

[tool.flake8]
max-line-length = 88
ignore = ["C901", "E203", "W503"]
per-file-ignores = ["__init__.py:F401"]


[tool.pylint.messages_control]
disable = [
  "C0114", # importing numpy, galsim throw this error 
  "C0103", # ra, g1, g2 throw this error but are good names
  "R0913", # sometimes this is OK, as long as function still does one thing.
  "R0914", # same as above.
]
max-line-length = "88"
