name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install black flake8 pylint isort

      - name: Run black
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8 bpp/

      - name: Run pylint
        run: |
          pylint bpp/

      - name: Run isort
        run: |
          isort bpp/ --check-only
