name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install fftw3 (for galsim)
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install Package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flit
          flit install -s --deps all

      - name: Run black
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8 bpp/

      - name: Run pylint
        run: |
          pylint bpp/

      - name: Run isort
        run: |
          isort bpp/ --check-only

      - name: Run Tests
        run: |
          pytest --durations=0
